# Istio Usage Guidelines

This til provides information regarding Istio.

## Istio Installations
In this section provides step by step guideline istio installation.

* Create a namespace using the manifest given below:

```json
{ 
  "kind": "Namespace", 
  "apiVersion": "v1",
  "metadata": { 
    "name": "istio-system", 
    "labels": { 
      "name": "istio-system" 
    } 
  } 
}
```

Create the above namespace using the command given below:

```bash
$ sudo kubectl apply -f namespace-creation-script.yaml
```

* There are two ways to install istio in kubernetes cluster:

  * Method 1: Follow the guidelines given in this link to install `istio` using kubernetes manifests. 

  * Method 2: In this methid `HelmRelease` will be used for installation, `HelmRelease` manifest is given below:
  
  
```
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: istio
  namespace: istio-system
spec:
  releaseName: istio
  chart:
    repository: https://raw.githubusercontent.com/IBM/charts/master/repo/stable
    name: ibm-istio
    version: 1.0.5
  values:
    global:
      enableTracing: true
    tracing:
      enabled: true
    jaeger:
      ingress:
        enabled: true
    pilot:
      traceSampling: 1
```
Currently, I using [IBM's helm chart for istio](https://github.com/IBM/charts/tree/master/stable/ibm-istio).



## Enable Tracing
The above manifest will enable the istio tracing. To check whether tracing is enabled or not we will use the sample app provided by istio.

* Follow these [guidelines](https://istio.io/docs/examples/bookinfo/) to deploy the sample application.

* Deploy the xposer for enabling ingress, ask `ali` for its kubernetes manifest.

* Use the manifest given below to enable jeager ingress because the default configuration(using the helm chart value parameters) are not working correctly due to invalid documentation: 
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:    
    ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.class: external-ingress
  name: jaeger-query
spec:
  rules:
  - host: jaeger-query.stakater.com
    http:
      paths:
      - backend:
          serviceName: jaeger-query
          servicePort: 16686
```

* Ingress will take sometime before it is enabled.

* Each of the application service needs to be visible in the jeager services drop down as well as in the dependencies graph.

## Proxy(sidecar) Container Injection
There are two ways to inject sidecar(proxy) container:

* By default istio inserts sidecar containers automatically, to disable it set this `sidecarInjectorWebhook.enabled` flag to false.

* To manually inject sidecar use the instruction given on this [link](https://istio.io/docs/setup/kubernetes/additional-setup/sidecar-injection/#manual-sidecar-injection).

