# Istio Usage Guidelines



### Installations
In this section provides step by step guideline istio installation.

* Create a namespace using the manifest given below:
```json
{ 
  "kind": "Namespace", 
  "apiVersion": "v1", 
  "metadata": { 
    "name": "istio-system", 
    "labels": { 
      "name": "istio-system" 
    } 
  } 
}
```
Create the above namespace using the command given below:
```bash
$ sudo kubectl apply -f namespace-creation-script.yaml
```

* Download the release from the [release page](https://github.com/istio/istio/releases/):

* Untar the release file.

* Install all the CRDs required by istio. CRDs are located at this location `install/kubernetes/helm/istio-init/files`. Command to do it is given below:
```
$ sudo kubectl apply -f *.yaml -n kube-system
```

To check weather CRDs are created or not use this command:
```bash
$ kubectl get crds | grep 'istio.io\|certmanager.k8s.io' | wc -l
```

* Deploy the istio using the Helm release, for now I using [IBM's helm chart](https://github.com/IBM/charts/tree/master/stable/ibm-istio). Manifest given below deploy istio with no modification in default parameters:
```
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: istio
  namespace: istio-system
spec:
  releaseName: istio
  chart:
    repository: https://raw.githubusercontent.com/IBM/charts/master/repo/stable
    name: ibm-istio
    version: 1.0.5
```


### Proxy(sidecar) Container Injection
There are two ways to inject sidecar(proxy) container:

* By default istio inserts sidecar containers automatically, to disable it set this `sidecarInjectorWebhook.enabled` flag to false.

* To manually inject sidecar use the instruction given on this [link](https://istio.io/docs/setup/kubernetes/additional-setup/sidecar-injection/#manual-sidecar-injection).

